From Maniunfold.ShouldOffer Require Export
  OneSorted.MultiplicativePositiveOperationNotations
  OneSorted.MultiplicativeNaturalOperationNotations
  OneSorted.MultiplicativeIntegerOperationNotations.
