struct empty {}

struct poly {
  1: required map<i32, double> coeffs;
  2: required double point;
}

enum request_type {
  EXIT = 0,
  EVAL = 1
}

union request_data {
  1: optional poly eval;
  2: optional empty exit;
}

struct request {
  1: required request_type type;
  2: required request_data data;
}

struct response {
  1: required double value;
}
